INSERT INTO dbblog.sys_param (id, par_key, par_value, menu_url, type) VALUES (2, 0, '一级', '/operation-category', 'CATEGORY_RANK');
INSERT INTO dbblog.sys_param (id, par_key, par_value, menu_url, type) VALUES (3, 1, '二级', '/operation-category', 'CATEGORY_RANK');
INSERT INTO dbblog.sys_param (id, par_key, par_value, menu_url, type) VALUES (4, 2, '三级', '/operation-category', 'CATEGORY_RANK');
INSERT INTO dbblog.sys_param (id, par_key, par_value, menu_url, type) VALUES (7, 0, '小图片', '/article-addOrUpdate', 'ARTICLE_COVER_TYPE');
INSERT INTO dbblog.sys_param (id, par_key, par_value, menu_url, type) VALUES (8, 1, '大图片', '/article-addOrUpdate', 'ARTICLE_COVER_TYPE');
INSERT INTO dbblog.sys_param (id, par_key, par_value, menu_url, type) VALUES (9, 2, '无图片', '/article-addOrUpdate', 'ARTICLE_COVER_TYPE');
INSERT INTO dbblog.sys_param (id, par_key, par_value, menu_url, type) VALUES (10, 0, '文章', null, 'MODULE_TYPE');
INSERT INTO dbblog.sys_param (id, par_key, par_value, menu_url, type) VALUES (11, 1, '图书', null, 'MODULE_TYPE');
INSERT INTO dbblog.sys_param (id, par_key, par_value, menu_url, type) VALUES (12, 2, '笔记', null, 'MODULE_TYPE');